# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38f2c8fc94bdfb165d0e74c08ec3ef1d79785b4572d8922b35aeadc60ec38cb14ec395f2b53acb78685071bbd8262e2bf1d3f25b6f3f10d9833b95fc2b6c5f3d

test:
  secret_key_base: 6cd79b2de3e11bc8593e576d182ba8892f52bfa029b5ad42b2ca4995fff2a268d799852429e01c94eda00ce4e0f4360f16189dd308821bc617ad01b85311ed7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
